<script lang="ts" context="module">
    import { writable } from "svelte/store";
    import type { Writable } from "svelte/store";

    type ThemeProperties = {
        [key: string]: string;
    };

    const themes: { [key: string]: ThemeProperties } = {
        default: {
            "--background": "#f5f5f5",
            "--light-background": "#ffffff",
            "--surface": "#eeeeee",
            "--primary-text": "#31363f",
            "--secondary-text": "#dde6ed",
            "--dark-text": "#111111",
            "--divider": "#dde6ed",
            "--shadow": "rgba(0, 0, 0, 0.25)",
            "--primary": "#526d82",
            "--secondary": "#9db2bf",
            "--warning": "#ffd966",
            "--error": "#f28b82",
            "--info": "#7ea8d7",
            "--success": "#90c695",
            "--dropdown-box-shadow": "rgba(162, 206, 209, 0.7)",
            "--group-card-hover": "#f0f0f0",
            "--seperator": "#cccccc",
            "--select-background-color": "#f3f4f6",
            "--select-text-color": "#374151",
            "--select-focus-border-color": "#2563eb",
            "--select-focus-box-shadow": "rgba(37, 99, 235, 0.3)",
        },
        darkTheme: {
            "--background": "#1a1a1a",
            "--light-background": "#2e2e2e",
            "--surface": "#333333",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#b0b0b0",
            "--dark-text": "#ffffff",
            "--divider": "#555555",
            "--shadow": "rgba(0, 0, 0, 0.5)",
            "--primary": "#3a6ea5",
            "--secondary": "#9eb3c2",
            "--warning": "#e9c46a",
            "--error": "#e76f51",
            "--info": "#64a3f7",
            "--success": "#81c784",
            "--dropdown-box-shadow": "rgba(58, 110, 165, 0.7)",
            "--group-card-hover": "#404040",
            "--seperator": "#666666",
            "--select-background-color": "#3b3b3b",
            "--select-text-color": "#d1d5db",
            "--select-focus-border-color": "#2563eb",
            "--select-focus-box-shadow": "rgba(37, 99, 235, 0.5)",
        },
        lightBlueTheme: {
            "--background": "#e0f7fa",
            "--light-background": "#ffffff",
            "--surface": "#b2ebf2",
            "--primary-text": "#004d40",
            "--secondary-text": "#00796b",
            "--dark-text": "#00251a",
            "--divider": "#80deea",
            "--shadow": "rgba(0, 77, 64, 0.25)",
            "--primary": "#00796b",
            "--secondary": "#004d40",
            "--warning": "#ffb74d",
            "--error": "#e57373",
            "--info": "#64b5f6",
            "--success": "#81c784",
            "--dropdown-box-shadow": "rgba(0, 121, 107, 0.7)",
            "--group-card-hover": "#b2dfdb",
            "--seperator": "#80cbc4",
            "--select-background-color": "#e0f2f1",
            "--select-text-color": "#004d40",
            "--select-focus-border-color": "#00796b",
            "--select-focus-box-shadow": "rgba(0, 121, 107, 0.3)",
        },
        creamTheme: {
            "--background": "#f0f0e9",
            "--light-background": "#ffffff",
            "--surface": "#d9d9d1",
            "--primary-text": "#4e4e4e",
            "--secondary-text": "#7d7d7d",
            "--dark-text": "#1c1c1c",
            "--divider": "#bfbfbf",
            "--shadow": "rgba(76, 76, 76, 0.25)",
            "--primary": "#8c7b75",
            "--secondary": "#b29e96",
            "--warning": "#f4a261",
            "--error": "#e76f51",
            "--info": "#6d9eeb",
            "--success": "#9acd32",
            "--dropdown-box-shadow": "rgba(140, 123, 117, 0.7)",
            "--group-card-hover": "#ece5e0",
            "--seperator": "#ccc5be",
            "--select-background-color": "#ebe7e2",
            "--select-text-color": "#4e4e4e",
            "--select-focus-border-color": "#8c7b75",
            "--select-focus-box-shadow": "rgba(140, 123, 117, 0.3)",
        },
        neutralTheme: {
            "--background": "#f5f5f5",
            "--light-background": "#ffffff",
            "--surface": "#e0e0e0",
            "--primary-text": "#212121",
            "--secondary-text": "#757575",
            "--dark-text": "#000000",
            "--divider": "#bdbdbd",
            "--shadow": "rgba(33, 33, 33, 0.25)",
            "--primary": "#3f51b5",
            "--secondary": "#ff4081",
            "--warning": "#ffa000",
            "--error": "#d32f2f",
            "--info": "#1976d2",
            "--success": "#388e3c",
            "--dropdown-box-shadow": "rgba(63, 81, 181, 0.7)",
            "--group-card-hover": "#e8eaf6",
            "--seperator": "#c5cae9",
            "--select-background-color": "#f5f5f5",
            "--select-text-color": "#212121",
            "--select-focus-border-color": "#3f51b5",
            "--select-focus-box-shadow": "rgba(63, 81, 181, 0.3)",
        },
        blueSkyTheme: {
            "--background": "#e3f2fd",
            "--light-background": "#ffffff",
            "--surface": "#bbdefb",
            "--primary-text": "#0d47a1",
            "--secondary-text": "#5472d3",
            "--dark-text": "#002171",
            "--divider": "#90caf9",
            "--shadow": "rgba(13, 71, 161, 0.25)",
            "--primary": "#1e88e5",
            "--secondary": "#64b5f6",
            "--warning": "#ffca28",
            "--error": "#e53935",
            "--info": "#29b6f6",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(30, 136, 229, 0.7)",
            "--group-card-hover": "#e1f5fe",
            "--seperator": "#b3e5fc",
            "--select-background-color": "#e3f2fd",
            "--select-text-color": "#0d47a1",
            "--select-focus-border-color": "#1e88e5",
            "--select-focus-box-shadow": "rgba(30, 136, 229, 0.3)",
        },
        darkGrayNeonTheme: {
            "--background": "#2c2c2c",
            "--light-background": "#3d3d3d",
            "--surface": "#4a4a4a",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#b0b0b0",
            "--dark-text": "#ffffff",
            "--divider": "#616161",
            "--shadow": "rgba(0, 0, 0, 0.7)",
            "--primary": "#8e24aa",
            "--secondary": "#d81b60",
            "--warning": "#ffa726",
            "--error": "#e53935",
            "--info": "#29b6f6",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(142, 36, 170, 0.7)",
            "--group-card-hover": "#424242",
            "--seperator": "#757575",
            "--select-background-color": "#3d3d3d",
            "--select-text-color": "#e0e0e0",
            "--select-focus-border-color": "#8e24aa",
            "--select-focus-box-shadow": "rgba(142, 36, 170, 0.3)",
        },
        neonGreenTheme: {
            "--background": "#0d0d0d",
            "--light-background": "#1a1a1a",
            "--surface": "#262626",
            "--primary-text": "#ffffff",
            "--secondary-text": "#a1a1a1",
            "--dark-text": "#e0e0e0",
            "--divider": "#333333",
            "--shadow": "rgba(0, 0, 0, 0.7)",
            "--primary": "#00ff7f",
            "--secondary": "#ff00ff",
            "--warning": "#ffea00",
            "--error": "#ff1744",
            "--info": "#00e5ff",
            "--success": "#76ff03",
            "--dropdown-box-shadow": "rgba(0, 255, 127, 0.7)",
            "--group-card-hover": "#1f1f1f",
            "--seperator": "#404040",
            "--select-background-color": "#1a1a1a",
            "--select-text-color": "#ffffff",
            "--select-focus-border-color": "#00ff7f",
            "--select-focus-box-shadow": "rgba(0, 255, 127, 0.3)",
        },
        rainbowTheme: {
            "--background": "#000000",
            "--light-background": "#1a1a1a",
            "--surface": "#262626",
            "--primary-text": "#ffffff",
            "--secondary-text": "#a1a1a1",
            "--dark-text": "#e0e0e0",
            "--divider": "#333333",
            "--shadow": "rgba(0, 0, 0, 0.7)",
            "--primary": "#ff0000",
            "--secondary": "#ff7f00",
            "--tertiary": "#ffff00",
            "--quaternary": "#00ff00",
            "--quinary": "#0000ff",
            "--senary": "#4b0082",
            "--septenary": "#8b00ff",
            "--warning": "#ffa726",
            "--error": "#ff1744",
            "--info": "#00e5ff",
            "--success": "#76ff03",
            "--dropdown-box-shadow": "rgba(255, 0, 0, 0.7)",
            "--group-card-hover": "#1f1f1f",
            "--seperator": "#404040",
            "--select-background-color": "#1a1a1a",
            "--select-text-color": "#ffffff",
            "--select-focus-border-color": "#ff0000",
            "--select-focus-box-shadow": "rgba(255, 0, 0, 0.3)",
        },
        darkTurquoiseTheme: {
            "--background": "#121212",
            "--light-background": "#1e1e1e",
            "--surface": "#2c2c2c",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#bdbdbd",
            "--dark-text": "#ffffff",
            "--divider": "#484848",
            "--shadow": "rgba(0, 0, 0, 0.7)",
            "--primary": "#00bcd4",
            "--secondary": "#ff4081",
            "--tertiary": "#ffea00",
            "--quaternary": "#76ff03",
            "--warning": "#ffab00",
            "--error": "#ff5252",
            "--info": "#40c4ff",
            "--success": "#69f0ae",
            "--dropdown-box-shadow": "rgba(0, 188, 212, 0.7)",
            "--group-card-hover": "#1e1e1e",
            "--seperator": "#484848",
            "--select-background-color": "#2c2c2c",
            "--select-text-color": "#e0e0e0",
            "--select-focus-border-color": "#00bcd4",
            "--select-focus-box-shadow": "rgba(0, 188, 212, 0.3)",
        },
        darkBlueTheme: {
            "--background": "#0b0c10",
            "--light-background": "#1f2833",
            "--surface": "#2c3e50",
            "--primary-text": "#c5c6c7",
            "--secondary-text": "#66fcf1",
            "--dark-text": "#ffffff",
            "--divider": "#45a29e",
            "--shadow": "rgba(11, 12, 16, 0.7)",
            "--primary": "#66fcf1",
            "--secondary": "#45a29e",
            "--warning": "#f39c12",
            "--error": "#e74c3c",
            "--info": "#3498db",
            "--success": "#2ecc71",
            "--dropdown-box-shadow": "rgba(102, 252, 241, 0.7)",
            "--group-card-hover": "#1f2833",
            "--seperator": "#34495e",
            "--select-background-color": "#1f2833",
            "--select-text-color": "#c5c6c7",
            "--select-focus-border-color": "#66fcf1",
            "--select-focus-box-shadow": "rgba(102, 252, 241, 0.3)",
        },
        pinkFuchsiaTheme: {
            "--background": "#1a1a1a",
            "--light-background": "#2e2e2e",
            "--surface": "#3e3e3e",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#ff00ff",
            "--dark-text": "#ffffff",
            "--divider": "#ff69b4",
            "--shadow": "rgba(26, 26, 26, 0.7)",
            "--primary": "#ff00ff",
            "--secondary": "#ff69b4",
            "--warning": "#ffb74d",
            "--error": "#ff1744",
            "--info": "#1e90ff",
            "--success": "#32cd32",
            "--dropdown-box-shadow": "rgba(255, 0, 255, 0.7)",
            "--group-card-hover": "#2e2e2e",
            "--seperator": "#ff69b4",
            "--select-background-color": "#2e2e2e",
            "--select-text-color": "#ff00ff",
            "--select-focus-border-color": "#ff00ff",
            "--select-focus-box-shadow": "rgba(255, 0, 255, 0.3)",
        },
        coralTheme: {
            "--background": "#ff6f61",
            "--light-background": "#ffe6e1",
            "--surface": "#ffcccb",
            "--primary-text": "#4e342e",
            "--secondary-text": "#795548",
            "--dark-text": "#3e2723",
            "--divider": "#ffab91",
            "--shadow": "rgba(255, 111, 97, 0.5)",
            "--primary": "#ff5722",
            "--secondary": "#ff8a65",
            "--warning": "#ffa726",
            "--error": "#e53935",
            "--info": "#4fc3f7",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(255, 87, 34, 0.7)",
            "--group-card-hover": "#ffab91",
            "--seperator": "#ffcccb",
            "--select-background-color": "#ffe6e1",
            "--select-text-color": "#4e342e",
            "--select-focus-border-color": "#ff5722",
            "--select-focus-box-shadow": "rgba(255, 87, 34, 0.3)",
        },
        acidGreenTheme: {
            "--background": "#ccff00",
            "--light-background": "#e6ff80",
            "--surface": "#ccff99",
            "--primary-text": "#1b5e20",
            "--secondary-text": "#388e3c",
            "--dark-text": "#003300",
            "--divider": "#99cc00",
            "--shadow": "rgba(204, 255, 0, 0.5)",
            "--primary": "#76ff03",
            "--secondary": "#64dd17",
            "--warning": "#ffd600",
            "--error": "#d50000",
            "--info": "#00b0ff",
            "--success": "#00c853",
            "--dropdown-box-shadow": "rgba(118, 255, 3, 0.7)",
            "--group-card-hover": "#ccff99",
            "--seperator": "#ccff66",
            "--select-background-color": "#e6ff80",
            "--select-text-color": "#1b5e20",
            "--select-focus-border-color": "#76ff03",
            "--select-focus-box-shadow": "rgba(118, 255, 3, 0.3)",
        },
        intensePurpleTheme: {
            "--background": "#2d0c57",
            "--light-background": "#3e165f",
            "--surface": "#563d7c",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#b0b0b0",
            "--dark-text": "#ffffff",
            "--divider": "#7851a9",
            "--shadow": "rgba(45, 12, 87, 0.7)",
            "--primary": "#9c27b0",
            "--secondary": "#ba68c8",
            "--warning": "#fbc02d",
            "--error": "#e53935",
            "--info": "#1e88e5",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(156, 39, 176, 0.7)",
            "--group-card-hover": "#4a148c",
            "--seperator": "#7b1fa2",
            "--select-background-color": "#3e165f",
            "--select-text-color": "#e0e0e0",
            "--select-focus-border-color": "#9c27b0",
            "--select-focus-box-shadow": "rgba(156, 39, 176, 0.3)",
        },
        brightOrangeTheme: {
            "--background": "#ff7043",
            "--light-background": "#ff8a65",
            "--surface": "#ffab91",
            "--primary-text": "#4e342e",
            "--secondary-text": "#6d4c41",
            "--dark-text": "#3e2723",
            "--divider": "#ffccbc",
            "--shadow": "rgba(255, 112, 67, 0.5)",
            "--primary": "#ff5722",
            "--secondary": "#ff7043",
            "--warning": "#ffeb3b",
            "--error": "#d32f2f",
            "--info": "#29b6f6",
            "--success": "#81c784",
            "--dropdown-box-shadow": "rgba(255, 87, 34, 0.7)",
            "--group-card-hover": "#ff8a65",
            "--seperator": "#ffccbc",
            "--select-background-color": "#ffab91",
            "--select-text-color": "#4e342e",
            "--select-focus-border-color": "#ff5722",
            "--select-focus-box-shadow": "rgba(255, 87, 34, 0.3)",
        },
        darkGreenTheme: {
            "--background": "#0a0f0d",
            "--light-background": "#1b2a23",
            "--surface": "#2e3d35",
            "--primary-text": "#d1e8e4",
            "--secondary-text": "#a7d4cb",
            "--dark-text": "#e0f2f1",
            "--divider": "#4b615c",
            "--shadow": "rgba(10, 15, 13, 0.7)",
            "--primary": "#26a69a",
            "--secondary": "#80cbc4",
            "--warning": "#ffab00",
            "--error": "#d50000",
            "--info": "#29b6f6",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(38, 166, 154, 0.7)",
            "--group-card-hover": "#1b2a23",
            "--seperator": "#4b615c",
            "--select-background-color": "#2e3d35",
            "--select-text-color": "#d1e8e4",
            "--select-focus-border-color": "#26a69a",
            "--select-focus-box-shadow": "rgba(38, 166, 154, 0.3)",
        },
        deepPurpleTheme: {
            "--background": "#1c0b19",
            "--light-background": "#2e1b29",
            "--surface": "#4a3a4f",
            "--primary-text": "#e0dfe5",
            "--secondary-text": "#bdb8c2",
            "--dark-text": "#ffffff",
            "--divider": "#6c5a7e",
            "--shadow": "rgba(28, 11, 25, 0.7)",
            "--primary": "#8e24aa",
            "--secondary": "#ba68c8",
            "--warning": "#ffab00",
            "--error": "#e53935",
            "--info": "#29b6f6",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(142, 36, 170, 0.7)",
            "--group-card-hover": "#2e1b29",
            "--seperator": "#6c5a7e",
            "--select-background-color": "#4a3a4f",
            "--select-text-color": "#e0dfe5",
            "--select-focus-border-color": "#8e24aa",
            "--select-focus-box-shadow": "rgba(142, 36, 170, 0.3)",
        },
        darkBlackTheme: {
            "--background": "#0a0a0a",
            "--light-background": "#1c1c1c",
            "--surface": "#2e2e2e",
            "--primary-text": "#f5f5f5",
            "--secondary-text": "#bdbdbd",
            "--dark-text": "#ffffff",
            "--divider": "#4f4f4f",
            "--shadow": "rgba(0, 0, 0, 0.7)",
            "--primary": "#bb86fc",
            "--secondary": "#03dac6",
            "--warning": "#ffd600",
            "--error": "#cf6679",
            "--info": "#2196f3",
            "--success": "#4caf50",
            "--dropdown-box-shadow": "rgba(187, 134, 252, 0.7)",
            "--group-card-hover": "#1c1c1c",
            "--seperator": "#4f4f4f",
            "--select-background-color": "#2e2e2e",
            "--select-text-color": "#f5f5f5",
            "--select-focus-border-color": "#bb86fc",
            "--select-focus-box-shadow": "rgba(187, 134, 252, 0.3)",
        },
        darkNavyTheme: {
            "--background": "#001f3f",
            "--light-background": "#002f5f",
            "--surface": "#004080",
            "--primary-text": "#f0f8ff",
            "--secondary-text": "#b0c4de",
            "--dark-text": "#ffffff",
            "--divider": "#5f9ea0",
            "--shadow": "rgba(0, 31, 63, 0.7)",
            "--primary": "#1e90ff",
            "--secondary": "#00ced1",
            "--warning": "#ffd700",
            "--error": "#ff4500",
            "--info": "#4682b4",
            "--success": "#32cd32",
            "--dropdown-box-shadow": "rgba(30, 144, 255, 0.7)",
            "--group-card-hover": "#002f5f",
            "--seperator": "#5f9ea0",
            "--select-background-color": "#004080",
            "--select-text-color": "#f0f8ff",
            "--select-focus-border-color": "#1e90ff",
            "--select-focus-box-shadow": "rgba(30, 144, 255, 0.3)",
        },
        solidBlackTheme: {
            "--background": "#000000",
            "--light-background": "#1a1a1a",
            "--surface": "#2e2e2e",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#bdbdbd",
            "--dark-text": "#ffffff",
            "--divider": "#4f4f4f",
            "--shadow": "rgba(0, 0, 0, 0.7)",
            "--primary": "#6200ea",
            "--secondary": "#03dac6",
            "--warning": "#ffd600",
            "--error": "#cf6679",
            "--info": "#2196f3",
            "--success": "#4caf50",
            "--dropdown-box-shadow": "rgba(98, 0, 234, 0.7)",
            "--group-card-hover": "#1a1a1a",
            "--seperator": "#4f4f4f",
            "--select-background-color": "#2e2e2e",
            "--select-text-color": "#e0e0e0",
            "--select-focus-border-color": "#6200ea",
            "--select-focus-box-shadow": "rgba(98, 0, 234, 0.3)",
        },
        darkSteelBlueTheme: {
            "--background": "#121212",
            "--light-background": "#1e1e1e",
            "--surface": "#2a2a2a",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#b0b0b0",
            "--dark-text": "#ffffff",
            "--divider": "#3f3f3f",
            "--shadow": "rgba(18, 18, 18, 0.7)",
            "--primary": "#607d8b",
            "--secondary": "#78909c",
            "--warning": "#ffb300",
            "--error": "#e53935",
            "--info": "#0288d1",
            "--success": "#43a047",
            "--dropdown-box-shadow": "rgba(96, 125, 139, 0.7)",
            "--group-card-hover": "#1e1e1e",
            "--seperator": "#3f3f3f",
            "--select-background-color": "#2a2a2a",
            "--select-text-color": "#e0e0e0",
            "--select-focus-border-color": "#607d8b",
            "--select-focus-box-shadow": "rgba(96, 125, 139, 0.3)",
        },
        darkGrayTheme: {
            "--background": "#1a1a1a",
            "--light-background": "#2e2e2e",
            "--surface": "#404040",
            "--primary-text": "#d0d0d0",
            "--secondary-text": "#a0a0a0",
            "--dark-text": "#ffffff",
            "--divider": "#555555",
            "--shadow": "rgba(26, 26, 26, 0.7)",
            "--primary": "#8d8d8d",
            "--secondary": "#b0b0b0",
            "--warning": "#ffa000",
            "--error": "#e64a19",
            "--info": "#1976d2",
            "--success": "#388e3c",
            "--dropdown-box-shadow": "rgba(141, 141, 141, 0.7)",
            "--group-card-hover": "#2e2e2e",
            "--seperator": "#555555",
            "--select-background-color": "#404040",
            "--select-text-color": "#d0d0d0",
            "--select-focus-border-color": "#8d8d8d",
            "--select-focus-box-shadow": "rgba(141, 141, 141, 0.3)",
        },
        darkAnthraciteTheme: {
            "--background": "#181818",
            "--light-background": "#282828",
            "--surface": "#383838",
            "--primary-text": "#d3d3d3",
            "--secondary-text": "#a9a9a9",
            "--dark-text": "#ffffff",
            "--divider": "#505050",
            "--shadow": "rgba(24, 24, 24, 0.7)",
            "--primary": "#5e35b1",
            "--secondary": "#ff7043",
            "--warning": "#ffa000",
            "--error": "#d32f2f",
            "--info": "#1976d2",
            "--success": "#388e3c",
            "--dropdown-box-shadow": "rgba(94, 53, 177, 0.7)",
            "--group-card-hover": "#282828",
            "--seperator": "#505050",
            "--select-background-color": "#383838",
            "--select-text-color": "#d3d3d3",
            "--select-focus-border-color": "#5e35b1",
            "--select-focus-box-shadow": "rgba(94, 53, 177, 0.3)",
        },
        graphiteGrayTheme: {
            "--background": "#121212",
            "--light-background": "#1c1c1c",
            "--surface": "#333333",
            "--primary-text": "#e0e0e0",
            "--secondary-text": "#bdbdbd",
            "--dark-text": "#ffffff",
            "--divider": "#424242",
            "--shadow": "rgba(18, 18, 18, 0.7)",
            "--primary": "#3949ab",
            "--secondary": "#f50057",
            "--warning": "#ffab00",
            "--error": "#d32f2f",
            "--info": "#1976d2",
            "--success": "#388e3c",
            "--dropdown-box-shadow": "rgba(57, 73, 171, 0.7)",
            "--group-card-hover": "#1c1c1c",
            "--seperator": "#424242",
            "--select-background-color": "#333333",
            "--select-text-color": "#e0e0e0",
            "--select-focus-border-color": "#3949ab",
            "--select-focus-box-shadow": "rgba(57, 73, 171, 0.3)",
        },
        whiteTheme: {
            "--background": "#ffffff",
            "--light-background": "#f7f7f7",
            "--surface": "#e0e0e0",
            "--primary-text": "#212121",
            "--secondary-text": "#757575",
            "--dark-text": "#000000",
            "--divider": "#bdbdbd",
            "--shadow": "rgba(0, 0, 0, 0.1)",
            "--primary": "#3f51b5",
            "--secondary": "#ff4081",
            "--warning": "#ffc107",
            "--error": "#f44336",
            "--info": "#2196f3",
            "--success": "#4caf50",
            "--dropdown-box-shadow": "rgba(63, 81, 181, 0.3)",
            "--group-card-hover": "#f7f7f7",
            "--seperator": "#e0e0e0",
            "--select-background-color": "#ffffff",
            "--select-text-color": "#212121",
            "--select-focus-border-color": "#3f51b5",
            "--select-focus-box-shadow": "rgba(63, 81, 181, 0.3)",
        },
        lightGrayTheme: {
            "--background": "#fafafa",
            "--light-background": "#ffffff",
            "--surface": "#f0f0f0",
            "--primary-text": "#424242",
            "--secondary-text": "#9e9e9e",
            "--dark-text": "#000000",
            "--divider": "#e0e0e0",
            "--shadow": "rgba(0, 0, 0, 0.1)",
            "--primary": "#1976d2",
            "--secondary": "#c2185b",
            "--warning": "#ff9800",
            "--error": "#d32f2f",
            "--info": "#0288d1",
            "--success": "#388e3c",
            "--dropdown-box-shadow": "rgba(25, 118, 210, 0.3)",
            "--group-card-hover": "#f0f0f0",
            "--seperator": "#e0e0e0",
            "--select-background-color": "#ffffff",
            "--select-text-color": "#424242",
            "--select-focus-border-color": "#1976d2",
            "--select-focus-box-shadow": "rgba(25, 118, 210, 0.3)",
        },
        pureWhiteTheme: {
            "--background": "#ffffff",
            "--light-background": "#f8f9fa",
            "--surface": "#e9ecef",
            "--primary-text": "#343a40",
            "--secondary-text": "#6c757d",
            "--dark-text": "#000000",
            "--divider": "#dee2e6",
            "--shadow": "rgba(0, 0, 0, 0.1)",
            "--primary": "#007bff",
            "--secondary": "#6c757d",
            "--warning": "#ffc107",
            "--error": "#dc3545",
            "--info": "#17a2b8",
            "--success": "#28a745",
            "--dropdown-box-shadow": "rgba(0, 123, 255, 0.3)",
            "--group-card-hover": "#f8f9fa",
            "--seperator": "#dee2e6",
            "--select-background-color": "#ffffff",
            "--select-text-color": "#343a40",
            "--select-focus-border-color": "#007bff",
            "--select-focus-box-shadow": "rgba(0, 123, 255, 0.3)",
        },
        iceBlueTheme: {
            "--background": "#f0f8ff",
            "--light-background": "#ffffff",
            "--surface": "#e0eaf0",
            "--primary-text": "#2c3e50",
            "--secondary-text": "#7f8c8d",
            "--dark-text": "#000000",
            "--divider": "#bdc3c7",
            "--shadow": "rgba(44, 62, 80, 0.1)",
            "--primary": "#3498db",
            "--secondary": "#95a5a6",
            "--warning": "#f39c12",
            "--error": "#e74c3c",
            "--info": "#1abc9c",
            "--success": "#2ecc71",
            "--dropdown-box-shadow": "rgba(52, 152, 219, 0.3)",
            "--group-card-hover": "#ecf0f1",
            "--seperator": "#bdc3c7",
            "--select-background-color": "#f0f8ff",
            "--select-text-color": "#2c3e50",
            "--select-focus-border-color": "#3498db",
            "--select-focus-box-shadow": "rgba(52, 152, 219, 0.3)",
        },
        paleYellowTheme: {
            "--background": "#fffde7",
            "--light-background": "#fffff8",
            "--surface": "#fff9c4",
            "--primary-text": "#212121",
            "--secondary-text": "#757575",
            "--dark-text": "#000000",
            "--divider": "#e0e0e0",
            "--shadow": "rgba(0, 0, 0, 0.1)",
            "--primary": "#fbc02d",
            "--secondary": "#ffa000",
            "--warning": "#ffeb3b",
            "--error": "#f44336",
            "--info": "#29b6f6",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(251, 192, 45, 0.3)",
            "--group-card-hover": "#fffff8",
            "--seperator": "#e0e0e0",
            "--select-background-color": "#fffde7",
            "--select-text-color": "#212121",
            "--select-focus-border-color": "#fbc02d",
            "--select-focus-box-shadow": "rgba(251, 192, 45, 0.3)",
        },
        darkBlueGreenTheme: {
            "--background": "#0d1b2a",
            "--light-background": "#1b263b",
            "--surface": "#415a77",
            "--primary-text": "#e0e1dd",
            "--secondary-text": "#778da9",
            "--dark-text": "#ffffff",
            "--divider": "#4f5d75",
            "--shadow": "rgba(0, 0, 0, 0.3)",
            "--primary": "#1f7a8c",
            "--secondary": "#ff9f1c",
            "--warning": "#e71d36",
            "--error": "#ff4040",
            "--info": "#4dabf7",
            "--success": "#2ec4b6",
            "--dropdown-box-shadow": "rgba(31, 122, 140, 0.5)",
            "--group-card-hover": "#1b263b",
            "--seperator": "#4f5d75",
            "--select-background-color": "#415a77",
            "--select-text-color": "#e0e1dd",
            "--select-focus-border-color": "#1f7a8c",
            "--select-focus-box-shadow": "rgba(31, 122, 140, 0.3)",
        },
        darkTealTheme: {
            "--background": "#0a3d62",
            "--light-background": "#1e5f74",
            "--surface": "#3c787e",
            "--primary-text": "#e0e1dd",
            "--secondary-text": "#778d8e",
            "--dark-text": "#ffffff",
            "--divider": "#4f5d75",
            "--shadow": "rgba(0, 0, 0, 0.3)",
            "--primary": "#26a69a",
            "--secondary": "#ff7043",
            "--warning": "#ffa000",
            "--error": "#ef5350",
            "--info": "#42a5f5",
            "--success": "#66bb6a",
            "--dropdown-box-shadow": "rgba(38, 166, 154, 0.5)",
            "--group-card-hover": "#1e5f74",
            "--seperator": "#4f5d75",
            "--select-background-color": "#3c787e",
            "--select-text-color": "#e0e1dd",
            "--select-focus-border-color": "#26a69a",
            "--select-focus-box-shadow": "rgba(38, 166, 154, 0.3)",
        },
        silverGrayTheme: {
            "--background": "#1f1f1f" /* Dark gray background */,
            "--light-background": "#2e2e2e" /* Dark gray surface */,
            "--surface": "#3c3c3c" /* Medium gray surface */,
            "--primary-text": "#e0e0e0" /* Light gray primary text */,
            "--secondary-text": "#b0b0b0" /* Medium gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#505050" /* Medium gray divider */,
            "--shadow": "rgba(31, 31, 31, 0.7)" /* Dark gray shadow */,
            "--primary": "#76c7c0" /* Bright turquoise primary color */,
            "--secondary": "#ffab00" /* Bright yellow secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#ef5350" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(118, 199, 192, 0.5)" /* Primary color shadow */,
            "--group-card-hover": "#2e2e2e" /* Dark gray card hover color */,
            "--separator": "#505050" /* Medium gray separator */,
            "--select-background-color":
                "#3c3c3c" /* Medium gray select background color */,
            "--select-text-color": "#e0e0e0" /* Light gray select text color */,
            "--select-focus-border-color":
                "#76c7c0" /* Primary color focus border */,
            "--select-focus-box-shadow":
                "rgba(118, 199, 192, 0.3)" /* Primary color focus shadow */,
        },
        midnightBlueTheme: {
            "--background": "#0a1a2a" /* Dark blue background */,
            "--light-background": "#1a2a3a" /* Dark blue surface */,
            "--surface": "#2a3a4a" /* Medium blue surface */,
            "--primary-text": "#d0e0f0" /* Light blue-gray primary text */,
            "--secondary-text": "#a0b0c0" /* Medium blue-gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#3a4a5a" /* Medium blue-gray divider */,
            "--shadow": "rgba(10, 26, 42, 0.7)" /* Dark blue shadow */,
            "--primary": "#1f7a8c" /* Bright turquoise primary color */,
            "--secondary": "#ff9f1c" /* Bright orange secondary color */,
            "--warning": "#e71d36" /* Bright red warning color */,
            "--error": "#ff4040" /* Bright red error color */,
            "--info": "#4dabf7" /* Bright blue info color */,
            "--success": "#2ec4b6" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(31, 122, 140, 0.5)" /* Primary color shadow */,
            "--group-card-hover": "#1a2a3a" /* Dark blue card hover color */,
            "--separator": "#3a4a5a" /* Medium blue-gray separator */,
            "--select-background-color":
                "#2a3a4a" /* Medium blue select background color */,
            "--select-text-color":
                "#d0e0f0" /* Light blue-gray select text color */,
            "--select-focus-border-color":
                "#1f7a8c" /* Primary color focus border */,
            "--select-focus-box-shadow":
                "rgba(31, 122, 140, 0.3)" /* Primary color focus shadow */,
        },
        forestGreenTheme: {
            "--background": "#0a3d2a" /* Dark green background */,
            "--light-background": "#1a4d3a" /* Dark green surface */,
            "--surface": "#2a5d4a" /* Medium green surface */,
            "--primary-text": "#d0e0d0" /* Light green-gray primary text */,
            "--secondary-text":
                "#a0b0a0" /* Medium green-gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#3a5d4a" /* Medium green-gray divider */,
            "--shadow": "rgba(10, 61, 42, 0.7)" /* Dark green shadow */,
            "--primary": "#26a69a" /* Bright turquoise primary color */,
            "--secondary": "#ff7043" /* Bright orange secondary color */,
            "--warning": "#ffa000" /* Bright orange warning color */,
            "--error": "#ef5350" /* Bright red error color */,
            "--info": "#42a5f5" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(38, 166, 154, 0.5)" /* Primary color shadow */,
            "--group-card-hover": "#1a4d3a" /* Dark green card hover color */,
            "--separator": "#3a5d4a" /* Medium green-gray separator */,
            "--select-background-color":
                "#2a5d4a" /* Medium green select background color */,
            "--select-text-color":
                "#d0e0d0" /* Light green-gray select text color */,
            "--select-focus-border-color":
                "#26a69a" /* Primary color focus border */,
            "--select-focus-box-shadow":
                "rgba(38, 166, 154, 0.3)" /* Primary color focus shadow */,
        },
        blackAndWhiteTheme: {
            "--background": "#000000" /* Black background */,
            "--light-background": "#ffffff" /* White surface */,
            "--surface": "#f0f0f0" /* Light gray surface */,
            "--primary-text": "#000000" /* White primary text */,
            "--secondary-text": "#bdbdbd" /* Light gray secondary text */,
            "--dark-text": "#000000" /* Black text */,
            "--divider": "#4f4f4f" /* Dark gray divider */,
            "--shadow": "rgba(0, 0, 0, 0.7)" /* Black shadow */,
            "--primary": "#ffffff" /* White primary color */,
            "--secondary": "#bdbdbd" /* Light gray secondary color */,
            "--warning": "#ffc107" /* Yellow warning color */,
            "--error": "#f44336" /* Red error color */,
            "--info": "#2196f3" /* Blue info color */,
            "--success": "#4caf50" /* Green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 255, 255, 0.7)" /* White shadow */,
            "--group-card-hover": "#1a1a1a" /* Dark gray card hover color */,
            "--separator": "#4f4f4f" /* Dark gray separator */,
            "--select-background-color":
                "#2e2e2e" /* Dark gray select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#ffffff" /* White focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 255, 255, 0.3)" /* White focus shadow */,
        },
        elegantGrayTheme: {
            "--background": "#2e2e2e" /* Dark gray background */,
            "--light-background": "#3e3e3e" /* Medium gray surface */,
            "--surface": "#4e4e4e" /* Light gray surface */,
            "--primary-text": "#e0e0e0" /* Light gray primary text */,
            "--secondary-text": "#bdbdbd" /* Light gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#666666" /* Dark gray divider */,
            "--shadow": "rgba(46, 46, 46, 0.7)" /* Dark gray shadow */,
            "--primary": "#a0a0a0" /* Medium gray primary color */,
            "--secondary": "#bdbdbd" /* Light gray secondary color */,
            "--warning": "#ffc107" /* Yellow warning color */,
            "--error": "#e57373" /* Light red error color */,
            "--info": "#64b5f6" /* Light blue info color */,
            "--success": "#81c784" /* Light green success color */,
            "--dropdown-box-shadow":
                "rgba(160, 160, 160, 0.7)" /* Medium gray shadow */,
            "--group-card-hover": "#3e3e3e" /* Medium gray card hover color */,
            "--separator": "#666666" /* Dark gray separator */,
            "--select-background-color":
                "#4e4e4e" /* Light gray select background color */,
            "--select-text-color": "#e0e0e0" /* Light gray select text color */,
            "--select-focus-border-color":
                "#a0a0a0" /* Medium gray focus border color */,
            "--select-focus-box-shadow":
                "rgba(160, 160, 160, 0.3)" /* Medium gray focus shadow */,
        },
        slateGrayTheme: {
            "--background": "#1c1c1c" /* Very dark gray background */,
            "--light-background": "#2a2a2a" /* Dark gray surface */,
            "--surface": "#3a3a3a" /* Medium dark gray surface */,
            "--primary-text": "#d0d0d0" /* Light gray primary text */,
            "--secondary-text": "#a0a0a0" /* Gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#4a4a4a" /* Dark gray divider */,
            "--shadow": "rgba(28, 28, 28, 0.7)" /* Very dark gray shadow */,
            "--primary": "#5f5f5f" /* Medium gray primary color */,
            "--secondary": "#8d8d8d" /* Light gray secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#d32f2f" /* Bright red error color */,
            "--info": "#42a5f5" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(95, 95, 95, 0.7)" /* Medium gray shadow */,
            "--group-card-hover": "#2a2a2a" /* Dark gray card hover color */,
            "--separator": "#4a4a4a" /* Dark gray separator */,
            "--select-background-color":
                "#3a3a3a" /* Medium dark gray select background color */,
            "--select-text-color": "#d0d0d0" /* Light gray select text color */,
            "--select-focus-border-color":
                "#5f5f5f" /* Medium gray focus border color */,
            "--select-focus-box-shadow":
                "rgba(95, 95, 95, 0.3)" /* Medium gray focus shadow */,
        },
        urbanGrayTheme: {
            "--background": "#1b1b1b" /* Very dark gray background */,
            "--light-background": "#292929" /* Dark gray surface */,
            "--surface": "#373737" /* Medium dark gray surface */,
            "--primary-text": "#c0c0c0" /* Light gray primary text */,
            "--secondary-text": "#a0a0a0" /* Gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#484848" /* Dark gray divider */,
            "--shadow": "rgba(27, 27, 27, 0.7)" /* Very dark gray shadow */,
            "--primary": "#6d6d6d" /* Medium gray primary color */,
            "--secondary": "#9e9e9e" /* Light gray secondary color */,
            "--warning": "#ffa000" /* Bright orange warning color */,
            "--error": "#e64a19" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#4caf50" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(109, 109, 109, 0.7)" /* Medium gray shadow */,
            "--group-card-hover": "#292929" /* Dark gray card hover color */,
            "--separator": "#484848" /* Dark gray separator */,
            "--select-background-color":
                "#373737" /* Medium dark gray select background color */,
            "--select-text-color": "#c0c0c0" /* Light gray select text color */,
            "--select-focus-border-color":
                "#6d6d6d" /* Medium gray focus border color */,
            "--select-focus-box-shadow":
                "rgba(109, 109, 109, 0.3)" /* Medium gray focus shadow */,
        },
        midnightBlackTheme: {
            "--background": "#000000" /* Black background */,
            "--light-background": "#1a1a1a" /* Very dark gray surface */,
            "--surface": "#000000" /* Black surface as primary color */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#b0b0b0" /* Light gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#4f4f4f" /* Dark gray divider */,
            "--shadow": "rgba(0, 0, 0, 0.7)" /* Black shadow */,
            "--primary": "#000000" /* Black primary color (surface) */,
            "--secondary": "#9e9e9e" /* Light gray secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#e53935" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow": "rgba(0, 0, 0, 0.7)" /* Black shadow */,
            "--group-card-hover":
                "#1a1a1a" /* Very dark gray card hover color */,
            "--separator": "#4f4f4f" /* Dark gray separator */,
            "--select-background-color":
                "#1a1a1a" /* Very dark gray select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#000000" /* Black focus border color */,
            "--select-focus-box-shadow":
                "rgba(0, 0, 0, 0.3)" /* Black focus shadow */,
        },
        sunsetOrangeTheme: {
            "--background": "#ff7043" /* Sunset orange background */,
            "--light-background": "#ff8a65" /* Light sunset orange surface */,
            "--surface": "#ff7043" /* Sunset orange surface */,
            "--primary-text": "#3e2723" /* Dark brown primary text */,
            "--secondary-text": "#795548" /* Medium brown secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#ffccbc" /* Light orange divider */,
            "--shadow": "rgba(255, 112, 67, 0.5)" /* Sunset orange shadow */,
            "--primary": "#ff7043" /* Sunset orange primary color */,
            "--secondary": "#ffccbc" /* Light orange secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#e53935" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 112, 67, 0.7)" /* Sunset orange shadow */,
            "--group-card-hover":
                "#ff8a65" /* Light sunset orange card hover color */,
            "--separator": "#ffccbc" /* Light orange separator */,
            "--select-background-color":
                "#ff7043" /* Sunset orange select background color */,
            "--select-text-color": "#3e2723" /* Dark brown select text color */,
            "--select-focus-border-color":
                "#ff7043" /* Sunset orange focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 112, 67, 0.3)" /* Sunset orange focus shadow */,
        },
        oceanBlueTheme: {
            "--background": "#0277bd" /* Ocean blue background */,
            "--light-background": "#58a5f0" /* Light ocean blue surface */,
            "--surface": "#0277bd" /* Ocean blue surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#b3e5fc" /* Light blue secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#4fc3f7" /* Light blue divider */,
            "--shadow": "rgba(2, 119, 189, 0.5)" /* Ocean blue shadow */,
            "--primary": "#0277bd" /* Ocean blue primary color */,
            "--secondary": "#4fc3f7" /* Light blue secondary color */,
            "--warning": "#ffca28" /* Bright yellow warning color */,
            "--error": "#e53935" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(2, 119, 189, 0.7)" /* Ocean blue shadow */,
            "--group-card-hover":
                "#58a5f0" /* Light ocean blue card hover color */,
            "--separator": "#4fc3f7" /* Light blue separator */,
            "--select-background-color":
                "#0277bd" /* Ocean blue select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#0277bd" /* Ocean blue focus border color */,
            "--select-focus-box-shadow":
                "rgba(2, 119, 189, 0.3)" /* Ocean blue focus shadow */,
        },
        royalPurpleTheme: {
            "--background": "#6a1b9a" /* Royal purple background */,
            "--light-background": "#9c4dcc" /* Light royal purple surface */,
            "--surface": "#6a1b9a" /* Royal purple surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#e1bee7" /* Light purple secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#ba68c8" /* Light purple divider */,
            "--shadow": "rgba(106, 27, 154, 0.5)" /* Royal purple shadow */,
            "--primary": "#6a1b9a" /* Royal purple primary color */,
            "--secondary": "#ba68c8" /* Light purple secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#e53935" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(106, 27, 154, 0.7)" /* Royal purple shadow */,
            "--group-card-hover":
                "#9c4dcc" /* Light royal purple card hover color */,
            "--separator": "#ba68c8" /* Light purple separator */,
            "--select-background-color":
                "#6a1b9a" /* Royal purple select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#6a1b9a" /* Royal purple focus border color */,
            "--select-focus-box-shadow":
                "rgba(106, 27, 154, 0.3)" /* Royal purple focus shadow */,
        },
        emeraldGreenTheme: {
            "--background": "#2e7d32" /* Forest green background */,
            "--light-background": "#60ad5e" /* Light forest green surface */,
            "--surface": "#2e7d32" /* Forest green surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#a5d6a7" /* Light green secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#66bb6a" /* Light green divider */,
            "--shadow": "rgba(46, 125, 50, 0.5)" /* Forest green shadow */,
            "--primary": "#2e7d32" /* Forest green primary color */,
            "--secondary": "#66bb6a" /* Light green secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#e53935" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(46, 125, 50, 0.7)" /* Forest green shadow */,
            "--group-card-hover":
                "#60ad5e" /* Light forest green card hover color */,
            "--separator": "#66bb6a" /* Light green separator */,
            "--select-background-color":
                "#2e7d32" /* Forest green select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#2e7d32" /* Forest green focus border color */,
            "--select-focus-box-shadow":
                "rgba(46, 125, 50, 0.3)" /* Forest green focus shadow */,
        },
        crimsonRedTheme: {
            "--background": "#b71c1c" /* Crimson red background */,
            "--light-background": "#e57373" /* Light crimson red surface */,
            "--surface": "#b71c1c" /* Crimson red surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#ffcdd2" /* Light red secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#ef9a9a" /* Light red divider */,
            "--shadow": "rgba(183, 28, 28, 0.5)" /* Crimson red shadow */,
            "--primary": "#b71c1c" /* Crimson red primary color */,
            "--secondary": "#ef9a9a" /* Light red secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#d32f2f" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(183, 28, 28, 0.7)" /* Crimson red shadow */,
            "--group-card-hover":
                "#e57373" /* Light crimson red card hover color */,
            "--separator": "#ef9a9a" /* Light red separator */,
            "--select-background-color":
                "#b71c1c" /* Crimson red select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#b71c1c" /* Crimson red focus border color */,
            "--select-focus-box-shadow":
                "rgba(183, 28, 28, 0.3)" /* Crimson red focus shadow */,
        },
        skyBlueTheme: {
            "--background": "#0288d1" /* Sky blue background */,
            "--light-background": "#4fc3f7" /* Light sky blue surface */,
            "--surface": "#0288d1" /* Sky blue surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#b3e5fc" /* Light blue secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#81d4fa" /* Light blue divider */,
            "--shadow": "rgba(2, 136, 209, 0.5)" /* Sky blue shadow */,
            "--primary": "#0288d1" /* Sky blue primary color */,
            "--secondary": "#81d4fa" /* Light blue secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#e53935" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(2, 136, 209, 0.7)" /* Sky blue shadow */,
            "--group-card-hover":
                "#4fc3f7" /* Light sky blue card hover color */,
            "--separator": "#81d4fa" /* Light blue separator */,
            "--select-background-color":
                "#0288d1" /* Sky blue select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#0288d1" /* Sky blue focus border color */,
            "--select-focus-box-shadow":
                "rgba(2, 136, 209, 0.3)" /* Sky blue focus shadow */,
        },
        amberYellowTheme: {
            "--background": "#ffca28" /* Amber yellow background */,
            "--light-background": "#ffecb3" /* Light amber yellow surface */,
            "--surface": "#ffca28" /* Amber yellow surface */,
            "--primary-text": "#3e2723" /* Dark brown primary text */,
            "--secondary-text": "#795548" /* Medium brown secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#ffe082" /* Light yellow divider */,
            "--shadow": "rgba(255, 202, 40, 0.5)" /* Amber yellow shadow */,
            "--primary": "#ffca28" /* Amber yellow primary color */,
            "--secondary": "#ffe082" /* Light yellow secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#d32f2f" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 202, 40, 0.7)" /* Amber yellow shadow */,
            "--group-card-hover":
                "#ffecb3" /* Light amber yellow card hover color */,
            "--separator": "#ffe082" /* Light yellow separator */,
            "--select-background-color":
                "#ffca28" /* Amber yellow select background color */,
            "--select-text-color": "#3e2723" /* Dark brown select text color */,
            "--select-focus-border-color":
                "#ffca28" /* Amber yellow focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 202, 40, 0.3)" /* Amber yellow focus shadow */,
        },
        lavenderPurpleTheme: {
            "--background": "#9575cd" /* Lavender purple background */,
            "--light-background": "#d1c4e9" /* Light lavender purple surface */,
            "--surface": "#9575cd" /* Lavender purple surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#e1bee7" /* Light purple secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#b39ddb" /* Light purple divider */,
            "--shadow": "rgba(149, 117, 205, 0.5)" /* Lavender purple shadow */,
            "--primary": "#9575cd" /* Lavender purple primary color */,
            "--secondary": "#b39ddb" /* Light purple secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#d32f2f" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(149, 117, 205, 0.7)" /* Lavender purple shadow */,
            "--group-card-hover":
                "#d1c4e9" /* Light lavender purple card hover color */,
            "--separator": "#b39ddb" /* Light purple separator */,
            "--select-background-color":
                "#9575cd" /* Lavender purple select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#9575cd" /* Lavender purple focus border color */,
            "--select-focus-box-shadow":
                "rgba(149, 117, 205, 0.3)" /* Lavender purple focus shadow */,
        },
        coralPinkTheme: {
            "--background": "#ff6f61" /* Coral pink background */,
            "--light-background": "#ffb5a7" /* Light coral pink surface */,
            "--surface": "#ff6f61" /* Coral pink surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#ffcccb" /* Light pink secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#ff9a8d" /* Light pink divider */,
            "--shadow": "rgba(255, 111, 97, 0.5)" /* Coral pink shadow */,
            "--primary": "#ff6f61" /* Coral pink primary color */,
            "--secondary": "#ff9a8d" /* Light pink secondary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#e53935" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 111, 97, 0.7)" /* Coral pink shadow */,
            "--group-card-hover":
                "#ffb5a7" /* Light coral pink card hover color */,
            "--separator": "#ff9a8d" /* Light pink separator */,
            "--select-background-color":
                "#ff6f61" /* Coral pink select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#ff6f61" /* Coral pink focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 111, 97, 0.3)" /* Coral pink focus shadow */,
        },
        nebulaGlowTheme: {
            "--background": "#1c1c2e" /* Deep space blue background */,
            "--light-background": "#26264c" /* Dark blue surface */,
            "--surface": "#1c1c2e" /* Deep space blue surface */,
            "--primary-text": "#e0e0e0" /* Light gray primary text */,
            "--secondary-text": "#b0b0b0" /* Medium gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#3e3e5e" /* Dark blue divider */,
            "--shadow": "rgba(28, 28, 46, 0.7)" /* Deep space blue shadow */,
            "--primary": "#9c27b0" /* Nebula purple primary color */,
            "--secondary": "#03a9f4" /* Nebula blue secondary color */,
            "--tertiary": "#ffeb3b" /* Nebula yellow tertiary color */,
            "--quaternary": "#8bc34a" /* Nebula green quaternary color */,
            "--warning": "#ff9800" /* Bright orange warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#00bcd4" /* Bright cyan info color */,
            "--success": "#4caf50" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(156, 39, 176, 0.7)" /* Nebula purple shadow */,
            "--group-card-hover": "#26264c" /* Dark blue card hover color */,
            "--separator": "#3e3e5e" /* Dark blue separator */,
            "--select-background-color":
                "#1c1c2e" /* Deep space blue select background color */,
            "--select-text-color": "#e0e0e0" /* Light gray select text color */,
            "--select-focus-border-color":
                "#9c27b0" /* Nebula purple focus border color */,
            "--select-focus-box-shadow":
                "rgba(156, 39, 176, 0.3)" /* Nebula purple focus shadow */,
        },
        auroraBorealisTheme: {
            "--background": "#001f3f" /* Dark navy blue background */,
            "--light-background": "#00264d" /* Deep blue surface */,
            "--surface": "#001f3f" /* Dark navy blue surface */,
            "--primary-text": "#e0f7fa" /* Light cyan primary text */,
            "--secondary-text": "#80deea" /* Medium cyan secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#004d66" /* Deep cyan divider */,
            "--shadow": "rgba(0, 31, 63, 0.7)" /* Dark navy blue shadow */,
            "--primary": "#00e676" /* Bright green primary color */,
            "--secondary": "#1de9b6" /* Bright teal secondary color */,
            "--tertiary": "#ffeb3b" /* Bright yellow tertiary color */,
            "--quaternary": "#ff1744" /* Bright red quaternary color */,
            "--warning": "#ffc107" /* Bright orange warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#00bcd4" /* Bright cyan info color */,
            "--success": "#4caf50" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(0, 230, 118, 0.7)" /* Bright green shadow */,
            "--group-card-hover": "#00264d" /* Deep blue card hover color */,
            "--separator": "#004d66" /* Deep cyan separator */,
            "--select-background-color":
                "#001f3f" /* Dark navy blue select background color */,
            "--select-text-color": "#e0f7fa" /* Light cyan select text color */,
            "--select-focus-border-color":
                "#00e676" /* Bright green focus border color */,
            "--select-focus-box-shadow":
                "rgba(0, 230, 118, 0.3)" /* Bright green focus shadow */,
        },
        cyberpunkNeonTheme: {
            "--background": "#0d0d0d" /* Dark black background */,
            "--light-background": "#1a1a1a" /* Very dark gray surface */,
            "--surface": "#0d0d0d" /* Dark black surface */,
            "--primary-text": "#f5f5f5" /* Light gray primary text */,
            "--secondary-text": "#bdbdbd" /* Medium gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#333333" /* Dark gray divider */,
            "--shadow": "rgba(13, 13, 13, 0.7)" /* Dark black shadow */,
            "--primary": "#ff00ff" /* Bright magenta primary color */,
            "--secondary": "#00ffff" /* Bright cyan secondary color */,
            "--tertiary": "#ffea00" /* Bright yellow tertiary color */,
            "--quaternary": "#ff1744" /* Bright red quaternary color */,
            "--warning": "#ff9800" /* Bright orange warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#2196f3" /* Bright blue info color */,
            "--success": "#4caf50" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 0, 255, 0.7)" /* Bright magenta shadow */,
            "--group-card-hover":
                "#1a1a1a" /* Very dark gray card hover color */,
            "--separator": "#333333" /* Dark gray separator */,
            "--select-background-color":
                "#0d0d0d" /* Dark black select background color */,
            "--select-text-color": "#f5f5f5" /* Light gray select text color */,
            "--select-focus-border-color":
                "#ff00ff" /* Bright magenta focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 0, 255, 0.3)" /* Bright magenta focus shadow */,
        },
        solarFlareTheme: {
            "--background": "#4a0000" /* Deep red background */,
            "--light-background": "#660000" /* Dark red surface */,
            "--surface": "#4a0000" /* Deep red surface */,
            "--primary-text": "#ffcccb" /* Light red primary text */,
            "--secondary-text": "#ffc1c1" /* Medium red secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#990000" /* Dark red divider */,
            "--shadow": "rgba(74, 0, 0, 0.7)" /* Deep red shadow */,
            "--primary": "#ff4500" /* Bright orange-red primary color */,
            "--secondary": "#ff6347" /* Bright tomato secondary color */,
            "--tertiary": "#ffa07a" /* Light salmon tertiary color */,
            "--quaternary": "#ff8c00" /* Dark orange quaternary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 69, 0, 0.7)" /* Bright orange-red shadow */,
            "--group-card-hover": "#660000" /* Dark red card hover color */,
            "--separator": "#990000" /* Dark red separator */,
            "--select-background-color":
                "#4a0000" /* Deep red select background color */,
            "--select-text-color": "#ffcccb" /* Light red select text color */,
            "--select-focus-border-color":
                "#ff4500" /* Bright orange-red focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 69, 0, 0.3)" /* Bright orange-red focus shadow */,
        },
        tropicalRainforestTheme: {
            "--background": "#004d40" /* Deep teal background */,
            "--light-background": "#00796b" /* Dark teal surface */,
            "--surface": "#004d40" /* Deep teal surface */,
            "--primary-text": "#e0f2f1" /* Light cyan primary text */,
            "--secondary-text": "#b2dfdb" /* Medium cyan secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#00796b" /* Dark teal divider */,
            "--shadow": "rgba(0, 77, 64, 0.7)" /* Deep teal shadow */,
            "--primary": "#00bfa5" /* Bright aqua primary color */,
            "--secondary": "#1de9b6" /* Bright teal secondary color */,
            "--tertiary": "#00e676" /* Bright green tertiary color */,
            "--quaternary": "#76ff03" /* Lime green quaternary color */,
            "--warning": "#ffa726" /* Bright orange warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(0, 191, 165, 0.7)" /* Bright aqua shadow */,
            "--group-card-hover": "#00796b" /* Dark teal card hover color */,
            "--separator": "#00796b" /* Dark teal separator */,
            "--select-background-color":
                "#004d40" /* Deep teal select background color */,
            "--select-text-color": "#e0f2f1" /* Light cyan select text color */,
            "--select-focus-border-color":
                "#00bfa5" /* Bright aqua focus border color */,
            "--select-focus-box-shadow":
                "rgba(0, 191, 165, 0.3)" /* Bright aqua focus shadow */,
        },
        galacticPurpleTheme: {
            "--background": "#2e003e" /* Deep purple background */,
            "--light-background": "#4a0072" /* Dark purple surface */,
            "--surface": "#2e003e" /* Deep purple surface */,
            "--primary-text": "#e1bee7" /* Light lavender primary text */,
            "--secondary-text": "#ce93d8" /* Medium lavender secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#6a1b9a" /* Dark lavender divider */,
            "--shadow": "rgba(46, 0, 62, 0.7)" /* Deep purple shadow */,
            "--primary": "#d500f9" /* Bright magenta primary color */,
            "--secondary": "#aa00ff" /* Bright violet secondary color */,
            "--tertiary": "#e040fb" /* Bright pink tertiary color */,
            "--quaternary": "#e91e63" /* Bright pink quaternary color */,
            "--warning": "#ff4081" /* Bright pink warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#29b6f6" /* Bright blue info color */,
            "--success": "#66bb6a" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(213, 0, 249, 0.7)" /* Bright magenta shadow */,
            "--group-card-hover": "#4a0072" /* Dark purple card hover color */,
            "--separator": "#6a1b9a" /* Dark lavender separator */,
            "--select-background-color":
                "#2e003e" /* Deep purple select background color */,
            "--select-text-color":
                "#e1bee7" /* Light lavender select text color */,
            "--select-focus-border-color":
                "#d500f9" /* Bright magenta focus border color */,
            "--select-focus-box-shadow":
                "rgba(213, 0, 249, 0.3)" /* Bright magenta focus shadow */,
        },
        electricLimeTheme: {
            "--background": "#1a1a1a" /* Dark gray background */,
            "--light-background": "#333333" /* Medium dark gray surface */,
            "--surface": "#1a1a1a" /* Dark gray surface */,
            "--primary-text": "#d4ff00" /* Electric lime primary text */,
            "--secondary-text": "#a0a000" /* Medium lime secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#3d3d00" /* Dark lime divider */,
            "--shadow": "rgba(26, 26, 26, 0.7)" /* Dark gray shadow */,
            "--primary": "#d4ff00" /* Electric lime primary color */,
            "--secondary": "#a0a000" /* Medium lime secondary color */,
            "--tertiary": "#ccff33" /* Bright lime tertiary color */,
            "--quaternary": "#ffff00" /* Yellow quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(212, 255, 0, 0.7)" /* Electric lime shadow */,
            "--group-card-hover":
                "#333333" /* Medium dark gray card hover color */,
            "--separator": "#3d3d00" /* Dark lime separator */,
            "--select-background-color":
                "#1a1a1a" /* Dark gray select background color */,
            "--select-text-color":
                "#d4ff00" /* Electric lime select text color */,
            "--select-focus-border-color":
                "#d4ff00" /* Electric lime focus border color */,
            "--select-focus-box-shadow":
                "rgba(212, 255, 0, 0.3)" /* Electric lime focus shadow */,
        },
        sunsetPurpleTheme: {
            "--background": "#3e1a4d" /* Dark purple background */,
            "--light-background": "#562a6a" /* Medium dark purple surface */,
            "--surface": "#3e1a4d" /* Dark purple surface */,
            "--primary-text": "#ffb3ff" /* Light pink primary text */,
            "--secondary-text": "#d48fd4" /* Medium pink secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#7a478a" /* Dark pink divider */,
            "--shadow": "rgba(62, 26, 77, 0.7)" /* Dark purple shadow */,
            "--primary": "#ff33cc" /* Bright pink primary color */,
            "--secondary": "#ff66ff" /* Bright fuchsia secondary color */,
            "--tertiary": "#ff99ff" /* Light pink tertiary color */,
            "--quaternary": "#ff33ff" /* Bright magenta quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 51, 204, 0.7)" /* Bright pink shadow */,
            "--group-card-hover":
                "#562a6a" /* Medium dark purple card hover color */,
            "--separator": "#7a478a" /* Dark pink separator */,
            "--select-background-color":
                "#3e1a4d" /* Dark purple select background color */,
            "--select-text-color": "#ffb3ff" /* Light pink select text color */,
            "--select-focus-border-color":
                "#ff33cc" /* Bright pink focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 51, 204, 0.3)" /* Bright pink focus shadow */,
        },
        darkIceBlueTheme: {
            "--background": "#003366" /* Dark blue background */,
            "--light-background": "#004080" /* Medium dark blue surface */,
            "--surface": "#003366" /* Dark blue surface */,
            "--primary-text": "#b3d9ff" /* Light blue primary text */,
            "--secondary-text": "#80bfff" /* Medium blue secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#0066cc" /* Medium blue divider */,
            "--shadow": "rgba(0, 51, 102, 0.7)" /* Dark blue shadow */,
            "--primary": "#3399ff" /* Bright blue primary color */,
            "--secondary": "#66ccff" /* Light blue secondary color */,
            "--tertiary": "#99ccff" /* Sky blue tertiary color */,
            "--quaternary": "#00ccff" /* Bright cyan quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(51, 153, 255, 0.7)" /* Bright blue shadow */,
            "--group-card-hover":
                "#004080" /* Medium dark blue card hover color */,
            "--separator": "#0066cc" /* Medium blue separator */,
            "--select-background-color":
                "#003366" /* Dark blue select background color */,
            "--select-text-color": "#b3d9ff" /* Light blue select text color */,
            "--select-focus-border-color":
                "#3399ff" /* Bright blue focus border color */,
            "--select-focus-box-shadow":
                "rgba(51, 153, 255, 0.3)" /* Bright blue focus shadow */,
        },
        mysticJadeTheme: {
            "--background": "#004d40" /* Deep jade green background */,
            "--light-background": "#00695c" /* Dark jade green surface */,
            "--surface": "#004d40" /* Deep jade green surface */,
            "--primary-text": "#e0f2f1" /* Light mint green primary text */,
            "--secondary-text":
                "#b2dfdb" /* Medium mint green secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#00796b" /* Dark teal divider */,
            "--shadow": "rgba(0, 77, 64, 0.7)" /* Deep jade green shadow */,
            "--primary": "#00e676" /* Bright mint green primary color */,
            "--secondary": "#1de9b6" /* Bright aqua secondary color */,
            "--tertiary": "#00e5ff" /* Bright cyan tertiary color */,
            "--quaternary": "#76ff03" /* Bright lime quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(0, 230, 118, 0.7)" /* Bright mint green shadow */,
            "--group-card-hover":
                "#00695c" /* Dark jade green card hover color */,
            "--separator": "#00796b" /* Dark teal separator */,
            "--select-background-color":
                "#004d40" /* Deep jade green select background color */,
            "--select-text-color":
                "#e0f2f1" /* Light mint green select text color */,
            "--select-focus-border-color":
                "#00e676" /* Bright mint green focus border color */,
            "--select-focus-box-shadow":
                "rgba(0, 230, 118, 0.3)" /* Bright mint green focus shadow */,
        },
        solarEclipseTheme: {
            "--background": "#2c3e50" /* Deep navy blue background */,
            "--light-background": "#34495e" /* Dark navy blue surface */,
            "--surface": "#2c3e50" /* Deep navy blue surface */,
            "--primary-text": "#ecf0f1" /* Light gray primary text */,
            "--secondary-text": "#95a5a6" /* Medium gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#7f8c8d" /* Medium gray divider */,
            "--shadow": "rgba(44, 62, 80, 0.7)" /* Deep navy blue shadow */,
            "--primary": "#e74c3c" /* Bright red primary color */,
            "--secondary": "#f39c12" /* Bright orange secondary color */,
            "--tertiary": "#f1c40f" /* Bright yellow tertiary color */,
            "--quaternary": "#16a085" /* Bright teal quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#3498db" /* Bright blue info color */,
            "--success": "#2ecc71" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(231, 76, 60, 0.7)" /* Bright red shadow */,
            "--group-card-hover":
                "#34495e" /* Dark navy blue card hover color */,
            "--separator": "#7f8c8d" /* Medium gray separator */,
            "--select-background-color":
                "#2c3e50" /* Deep navy blue select background color */,
            "--select-text-color": "#ecf0f1" /* Light gray select text color */,
            "--select-focus-border-color":
                "#e74c3c" /* Bright red focus border color */,
            "--select-focus-box-shadow":
                "rgba(231, 76, 60, 0.3)" /* Bright red focus shadow */,
        },
        candylandTheme: {
            "--background": "#ff6f61" /* Bright coral background */,
            "--light-background": "#ffb5a7" /* Light coral surface */,
            "--surface": "#ff6f61" /* Bright coral surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#ffc1c1" /* Light pink secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#ff9a8d" /* Light pink divider */,
            "--shadow": "rgba(255, 111, 97, 0.5)" /* Bright coral shadow */,
            "--primary": "#ff6f61" /* Bright coral primary color */,
            "--secondary": "#ffcccb" /* Light pink secondary color */,
            "--tertiary": "#ff99ff" /* Light magenta tertiary color */,
            "--quaternary": "#ff33ff" /* Bright magenta quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 111, 97, 0.7)" /* Bright coral shadow */,
            "--group-card-hover": "#ffb5a7" /* Light coral card hover color */,
            "--separator": "#ff9a8d" /* Light pink separator */,
            "--select-background-color":
                "#ff6f61" /* Bright coral select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#ff6f61" /* Bright coral focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 111, 97, 0.3)" /* Bright coral focus shadow */,
        },
        twilightMeadowTheme: {
            "--background": "#003366" /* Dark blue background */,
            "--light-background": "#004080" /* Medium dark blue surface */,
            "--surface": "#003366" /* Dark blue surface */,
            "--primary-text": "#b3d9ff" /* Light blue primary text */,
            "--secondary-text": "#80bfff" /* Medium blue secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#0066cc" /* Medium blue divider */,
            "--shadow": "rgba(0, 51, 102, 0.7)" /* Dark blue shadow */,
            "--primary": "#3399ff" /* Bright blue primary color */,
            "--secondary": "#66ccff" /* Light blue secondary color */,
            "--tertiary": "#99ccff" /* Sky blue tertiary color */,
            "--quaternary": "#00ccff" /* Bright cyan quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(51, 153, 255, 0.7)" /* Bright blue shadow */,
            "--group-card-hover":
                "#004080" /* Medium dark blue card hover color */,
            "--separator": "#0066cc" /* Medium blue separator */,
            "--select-background-color":
                "#003366" /* Dark blue select background color */,
            "--select-text-color": "#b3d9ff" /* Light blue select text color */,
            "--select-focus-border-color":
                "#3399ff" /* Bright blue focus border color */,
            "--select-focus-box-shadow":
                "rgba(51, 153, 255, 0.3)" /* Bright blue focus shadow */,
        },
        royalGoldTheme: {
            "--background": "#333333" /* Dark gray background */,
            "--light-background": "#4f4f4f" /* Medium dark gray surface */,
            "--surface": "#333333" /* Dark gray surface */,
            "--primary-text": "#ffd700" /* Gold primary text */,
            "--secondary-text": "#ffec8b" /* Light gold secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#b8860b" /* Dark gold divider */,
            "--shadow": "rgba(51, 51, 51, 0.7)" /* Dark gray shadow */,
            "--primary": "#ffd700" /* Gold primary color */,
            "--secondary": "#ffec8b" /* Light gold secondary color */,
            "--tertiary": "#ffc107" /* Amber tertiary color */,
            "--quaternary": "#ff9800" /* Bright orange quaternary color */,
            "--warning": "#ffcc00" /* Bright yellow warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow": "rgba(255, 215, 0, 0.7)" /* Gold shadow */,
            "--group-card-hover":
                "#4f4f4f" /* Medium dark gray card hover color */,
            "--separator": "#b8860b" /* Dark gold separator */,
            "--select-background-color":
                "#333333" /* Dark gray select background color */,
            "--select-text-color": "#ffd700" /* Gold select text color */,
            "--select-focus-border-color":
                "#ffd700" /* Gold focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 215, 0, 0.3)" /* Gold focus shadow */,
        },
        raspberrySorbetTheme: {
            "--background": "#880e4f" /* Deep raspberry background */,
            "--light-background": "#ad1457" /* Dark raspberry surface */,
            "--surface": "#880e4f" /* Deep raspberry surface */,
            "--primary-text": "#ffc1e3" /* Light pink primary text */,
            "--secondary-text": "#ff80ab" /* Medium pink secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#d81b60" /* Dark pink divider */,
            "--shadow": "rgba(136, 14, 79, 0.7)" /* Deep raspberry shadow */,
            "--primary": "#f50057" /* Bright raspberry primary color */,
            "--secondary": "#ff4081" /* Bright pink secondary color */,
            "--tertiary": "#ff80ab" /* Light pink tertiary color */,
            "--quaternary": "#ff1744" /* Bright red quaternary color */,
            "--warning": "#ffcc00" /* Bright yellow warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(245, 0, 87, 0.7)" /* Bright raspberry shadow */,
            "--group-card-hover":
                "#ad1457" /* Dark raspberry card hover color */,
            "--separator": "#d81b60" /* Dark pink separator */,
            "--select-background-color":
                "#880e4f" /* Deep raspberry select background color */,
            "--select-text-color": "#ffc1e3" /* Light pink select text color */,
            "--select-focus-border-color":
                "#f50057" /* Bright raspberry focus border color */,
            "--select-focus-box-shadow":
                "rgba(245, 0, 87, 0.3)" /* Bright raspberry focus shadow */,
        },
        arcticFrostTheme: {
            "--background": "#001f3f" /* Deep navy blue background */,
            "--light-background": "#003366" /* Dark blue surface */,
            "--surface": "#001f3f" /* Deep navy blue surface */,
            "--primary-text": "#e0f7fa" /* Light cyan primary text */,
            "--secondary-text": "#80deea" /* Medium cyan secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#0077b6" /* Dark cyan divider */,
            "--shadow": "rgba(0, 31, 63, 0.7)" /* Deep navy blue shadow */,
            "--primary": "#00bcd4" /* Bright cyan primary color */,
            "--secondary": "#1de9b6" /* Bright teal secondary color */,
            "--tertiary": "#00e5ff" /* Bright light blue tertiary color */,
            "--quaternary": "#76ff03" /* Bright green quaternary color */,
            "--warning": "#ffcc00" /* Bright orange warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(0, 188, 212, 0.7)" /* Bright cyan shadow */,
            "--group-card-hover": "#003366" /* Dark blue card hover color */,
            "--separator": "#0077b6" /* Dark cyan separator */,
            "--select-background-color":
                "#001f3f" /* Deep navy blue select background color */,
            "--select-text-color": "#e0f7fa" /* Light cyan select text color */,
            "--select-focus-border-color":
                "#00bcd4" /* Bright cyan focus border color */,
            "--select-focus-box-shadow":
                "rgba(0, 188, 212, 0.3)" /* Bright cyan focus shadow */,
        },
        darkMatterTheme: {
            "--background": "#000000" /* Black background */,
            "--light-background": "#1a1a1a" /* Very dark gray surface */,
            "--surface": "#000000" /* Black surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#b0b0b0" /* Medium gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#333333" /* Dark gray divider */,
            "--shadow": "rgba(0, 0, 0, 0.7)" /* Black shadow */,
            "--primary": "#ffcc00" /* Bright yellow primary color */,
            "--secondary": "#ff9900" /* Bright orange secondary color */,
            "--tertiary": "#ff6600" /* Bright orange tertiary color */,
            "--quaternary": "#ff3300" /* Bright red quaternary color */,
            "--warning": "#ffcc00" /* Bright yellow warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 204, 0, 0.7)" /* Bright yellow shadow */,
            "--group-card-hover":
                "#1a1a1a" /* Very dark gray card hover color */,
            "--separator": "#333333" /* Dark gray separator */,
            "--select-background-color":
                "#000000" /* Black select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#ffcc00" /* Bright yellow focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 204, 0, 0.3)" /* Bright yellow focus shadow */,
        },
        cyberSunsetTheme: {
            "--background": "#1f1f1f" /* Dark gray background */,
            "--light-background": "#2e2e2e" /* Dark gray surface */,
            "--surface": "#ff6f61" /* Bright coral surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#ffcccb" /* Light pink secondary text */,
            "--dark-text": "#000000" /* Black text */,
            "--divider": "#ff9a8d" /* Light pink divider */,
            "--shadow": "rgba(31, 31, 31, 0.7)" /* Dark gray shadow */,
            "--primary": "#ff6f61" /* Bright coral primary color */,
            "--secondary": "#ffcccb" /* Light pink secondary color */,
            "--tertiary": "#ffc107" /* Amber tertiary color */,
            "--quaternary": "#ff9800" /* Bright orange quaternary color */,
            "--warning": "#ffcc00" /* Bright yellow warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 111, 97, 0.7)" /* Bright coral shadow */,
            "--group-card-hover": "#2e2e2e" /* Dark gray card hover color */,
            "--separator": "#ff9a8d" /* Light pink separator */,
            "--select-background-color":
                "#ff6f61" /* Bright coral select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#ff6f61" /* Bright coral focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 111, 97, 0.3)" /* Bright coral focus shadow */,
        },
        retroWaveTheme: {
            "--background": "#282828" /* Dark gray background */,
            "--light-background": "#404040" /* Medium dark gray surface */,
            "--surface": "#ff00ff" /* Neon pink surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#d1d1d1" /* Light gray secondary text */,
            "--dark-text": "#000000" /* Black text */,
            "--divider": "#ff69b4" /* Hot pink divider */,
            "--shadow": "rgba(40, 40, 40, 0.7)" /* Dark gray shadow */,
            "--primary": "#ff00ff" /* Neon pink primary color */,
            "--secondary": "#ff69b4" /* Hot pink secondary color */,
            "--tertiary": "#00ffff" /* Neon cyan tertiary color */,
            "--quaternary": "#ffea00" /* Neon yellow quaternary color */,
            "--warning": "#ffcc00" /* Bright yellow warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 0, 255, 0.7)" /* Neon pink shadow */,
            "--group-card-hover":
                "#404040" /* Medium dark gray card hover color */,
            "--separator": "#ff69b4" /* Hot pink separator */,
            "--select-background-color":
                "#ff00ff" /* Neon pink select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#ff00ff" /* Neon pink focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 0, 255, 0.3)" /* Neon pink focus shadow */,
        },
        oceanAbyssTheme: {
            "--background": "#0d1b2a" /* Dark blue background */,
            "--light-background": "#1b263b" /* Medium dark blue surface */,
            "--surface": "#4f6d7a" /* Slate blue surface */,
            "--primary-text": "#e0e1dd" /* Light gray primary text */,
            "--secondary-text": "#778da9" /* Medium gray secondary text */,
            "--dark-text": "#ffffff" /* White text */,
            "--divider": "#415a77" /* Medium blue divider */,
            "--shadow": "rgba(13, 27, 42, 0.7)" /* Dark blue shadow */,
            "--primary": "#4f6d7a" /* Slate blue primary color */,
            "--secondary": "#1c2541" /* Dark navy secondary color */,
            "--tertiary": "#0d3b66" /* Dark blue tertiary color */,
            "--quaternary": "#3a506b" /* Steel blue quaternary color */,
            "--warning": "#ffcc00" /* Bright yellow warning color */,
            "--error": "#ff0033" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(79, 109, 122, 0.7)" /* Slate blue shadow */,
            "--group-card-hover":
                "#1b263b" /* Medium dark blue card hover color */,
            "--separator": "#415a77" /* Medium blue separator */,
            "--select-background-color":
                "#4f6d7a" /* Slate blue select background color */,
            "--select-text-color": "#e0e1dd" /* Light gray select text color */,
            "--select-focus-border-color":
                "#4f6d7a" /* Slate blue focus border color */,
            "--select-focus-box-shadow":
                "rgba(79, 109, 122, 0.3)" /* Slate blue focus shadow */,
        },
        desertOasisTheme: {
            "--background": "#3e2723" /* Deep brown background */,
            "--light-background": "#5d4037" /* Medium brown surface */,
            "--surface": "#ffcc80" /* Light orange surface */,
            "--primary-text": "#ffffff" /* White primary text */,
            "--secondary-text": "#ffe0b2" /* Light orange secondary text */,
            "--dark-text": "#000000" /* Black text */,
            "--divider": "#ffab91" /* Light orange divider */,
            "--shadow": "rgba(62, 39, 35, 0.7)" /* Deep brown shadow */,
            "--primary": "#ff9800" /* Bright orange primary color */,
            "--secondary": "#ffb74d" /* Light orange secondary color */,
            "--tertiary": "#ffcc80" /* Pale orange tertiary color */,
            "--quaternary": "#ffa726" /* Bright orange quaternary color */,
            "--warning": "#ffcc00" /* Bright yellow warning color */,
            "--error": "#f44336" /* Bright red error color */,
            "--info": "#33ccff" /* Bright cyan info color */,
            "--success": "#66ff66" /* Bright green success color */,
            "--dropdown-box-shadow":
                "rgba(255, 152, 0, 0.7)" /* Bright orange shadow */,
            "--group-card-hover": "#5d4037" /* Medium brown card hover color */,
            "--separator": "#ffab91" /* Light orange separator */,
            "--select-background-color":
                "#ffcc80" /* Light orange select background color */,
            "--select-text-color": "#ffffff" /* White select text color */,
            "--select-focus-border-color":
                "#ff9800" /* Bright orange focus border color */,
            "--select-focus-box-shadow":
                "rgba(255, 152, 0, 0.3)" /* Bright orange focus shadow */,
        },
    };

    export function applyTheme(theme: string) {
        const themeProperties = themes[theme];
        for (const [property, value] of Object.entries(themeProperties)) {
            document.documentElement.style.setProperty(property, value);
        }
        currentTheme.set(theme);
        localStorage.setItem("selectedTheme", theme);
    }

    export const currentTheme: Writable<string> = writable("default");
</script>

<script lang="ts">
    import { onMount } from "svelte";

    onMount(() => {
        const savedTheme = localStorage.getItem("selectedTheme");
        if (savedTheme && themes[savedTheme]) {
            applyTheme(savedTheme);
        } else {
            applyTheme("default");
        }
    });
</script>

<div class="theme-switcher">
    <div class="grid grid-cols-12 gap-2">
        {#each Object.keys(themes) as theme}
            <button
                class="theme-button"
                style="background: linear-gradient(to right, {themes[theme][
                    '--surface'
                ]} 60%, {themes[theme]['--primary']} 80%, {themes[theme][
                    '--secondary'
                ]} 100%); color: {themes[theme]['--primary-text']};"
                on:click={() => applyTheme(theme)}
            >
                <!-- {theme
                    .replace(/([A-Z])/g, " $1")
                    .replace(/^./, (str) => str.toUpperCase())} -->
            </button>
        {/each}
    </div>
</div>

<style>
    .theme-switcher {
        display: flex;
        flex-wrap: wrap;
        gap: 10px;
    }

    .theme-button {
        padding: 5px;
        cursor: pointer;
        border: none;
        border-radius: 5px;
        transition:
            background-color 0.3s ease,
            color 0.3s ease;
        text-align: center;
        width: 75px;
        height: 45px;
    }
</style>
